### ISSUE TITLE
Rule 14: does double export make sense?

### ISSUE THREAD

**Issue by yadimon** [CarmenPopoviciu/protractor-testing-guidelines#24]
in the section: 
Rule-14: Use a single module.exports at the end of the Page Object file

in the example you make 2 exports.
But does such code example make any sense?

**Comment by robinj** [comment]
I think you are correct. In the avoid example, the latter export will overwrite the former. So rather than this: 

```javascript
/* avoid */

/* user-profile.page.js */
var UserProfilePage = function() {};
var UserSettingsPage = function() {};

module.exports = UserPropertiesPage;
module.exports = UserSettingsPage;
```

we could have this:

```javascript
/* avoid */

/* user-profile.page.js */
var UserProfilePage = function() {};
var UserSettingsPage = function() {};

module.exports.userPropertiesPage = UserPropertiesPage;
module.exports.userSettingsPage = UserSettingsPage;
```

That will, however, mean that Rule 14 will be effectively the same as Rule 13. I'll try to have a think about this and submit a PR tonight, but it does look like one of the rules will have to be made redundant in order to fix this issue.

**Comment by robinj** [comment]
@yadimon I have had a go at fixing this issue in #28. Do feel free to review it and let me know what you think
